name: r
channels:
  - conda-forge
  - bioconda
  - defaults
  - r
dependencies:
  - bioconductor-annotate=1.56.0=r3.4.1_0
  - bioconductor-annotationdbi=1.40.0=r3.4.1_0
  - bioconductor-biobase=2.38.0=r3.4.1_0
  - bioconductor-biocgenerics=0.24.0=r3.4.1_0
  - bioconductor-biocinstaller=1.28.0=r3.4.1_0
  - bioconductor-biocparallel=1.12.0=r3.4.1_0
  - bioconductor-genefilter=1.60.0=r3.4.1_0
  - bioconductor-geneplotter=1.56.0=r3.4.1_0
  - bioconductor-graph=1.56.0=r3.4.1_0
  - bioconductor-gseabase=1.40.0=r3.4.1_0
  - bioconductor-gsva=1.26.0=r3.4.1_0
  - bioconductor-iranges=2.12.0=r3.4.1_0
  - bioconductor-limma=3.34.9=r3.4.1_0
  - bioconductor-preprocesscore=1.40.0=r3.4.1_0
  - bioconductor-s4vectors=0.16.0=r3.4.1_0
  - bioconductor-sva=3.26.0=r3.4.1_0
  - bzip2=1.0.6=1
  - ca-certificates=2018.4.16=0
  - cairo=1.14.10=0
  - curl=7.60.0=0
  - fontconfig=2.12.6=0
  - freetype=2.8.1=0
  - gettext=0.19.8.1=0
  - glib=2.55.0=0
  - gmp=6.1.2=0
  - graphite2=1.3.11=0
  - gsl=2.1=2
  - harfbuzz=1.7.6=0
  - icu=58.2=0
  - jpeg=9b=2
  - krb5=1.14.6=0
  - libffi=3.2.1=3
  - libiconv=1.15=0
  - libpng=1.6.34=0
  - libssh2=1.8.0=2
  - libtiff=4.0.9=0
  - libuuid=1.0.3=1
  - libxcb=1.13=0
  - libxml2=2.9.8=0
  - ncurses=5.9=10
  - openblas=0.2.20=8
  - openssl=1.0.2o=0
  - pandoc=2.2.1=0
  - pango=1.40.14=0
  - pcre=8.39=0
  - pixman=0.34.0=2
  - r-assertthat=0.2.0=r3.4.1_0
  - r-backports=1.1.2=r3.4.1_0
  - r-base=3.4.1=4
  - r-base64enc=0.1_3=r3.4.1_0
  - r-bh=1.66.0_1=r3.4.1_0
  - r-bindr=0.1.1=r3.4.1_0
  - r-bindrcpp=0.2=r3.4.1_0
  - r-bit=1.1_12=r3.4.1_0
  - r-bit64=0.9_5=r3.4.1_0
  - r-bitops=1.0_6=r3.4.1_0
  - r-blob=1.1.1=r3.4.1_0
  - r-bookdown=0.6=r3.4.1_0
  - r-brew=1.0_6=r3.4.1_0
  - r-broom=0.4.4=r3.4.1_0
  - r-catools=1.17.1=r3.4.1_0
  - r-cellranger=1.1.0=r3.4.1_0
  - r-class=7.3_14=r3.4.1_0
  - r-cli=1.0.0=r3.4.1_0
  - r-cluster=2.0.6=r3.4.1_0
  - r-codetools=0.2_15=r3.4.1_0
  - r-colorspace=1.3_2=r3.4.1_0
  - r-commonmark=1.5=r341_0
  - r-cowplot=0.9.2=r3.4.1_0
  - r-crayon=1.3.4=r3.4.1_0
  - r-crosstalk=1.0.0=r3.4.1_0
  - r-curl=3.2=r3.4.1_0
  - r-data.tree=0.7.6=r341_0
  - r-dbi=1.0.0=r341_0
  - r-dbplyr=1.2.1=r341_0
  - r-desc=1.2.0=r3.4.1_0
  - r-devtools=1.13.5=r3.4.1_0
  - r-diagrammer=1.0.0=r3.4.1_0
  - r-dichromat=2.0_0=r3.4.1_0
  - r-digest=0.6.15=r3.4.1_0
  - r-domc=1.3.5=r3.4.1_0
  - r-doparallel=1.0.11=r3.4.1_0
  - r-downloader=0.4=r3.4.1_0
  - r-dplyr=0.7.4=r3.4.1_0
  - r-dt=0.4=r3.4.1_0
  - r-e1071=1.6_8=r3.4.1_0
  - r-evaluate=0.10.1=r3.4.1_0
  - r-forcats=0.3.0=r3.4.1_0
  - r-foreach=1.4.4=r3.4.1_0
  - r-foreign=0.8_67=r3.4.1_0
  - r-futile.logger=1.4.3=r3.4.1_0
  - r-futile.options=1.0.0=r3.4.1_0
  - r-ggplot2=2.2.1=r3.4.1_0
  - r-ggpubr=0.1.6=r3.4.1_0
  - r-ggrepel=0.8.0=r341_0
  - r-ggsci=2.8=r3.4.1_0
  - r-ggsignif=0.4.0=r3.4.1_0
  - r-git2r=0.21.0=r341h0c37787_0
  - r-glue=1.2.0=r3.4.1_0
  - r-gridbase=0.4_7=r3.4.1_0
  - r-gridextra=2.3=r3.4.1_0
  - r-gtable=0.2.0=r3.4.1_0
  - r-haven=1.1.1=r3.4.1_0
  - r-highr=0.7=r341_0
  - r-hms=0.3=r3.4.1_0
  - r-htmltools=0.3.6=r3.4.1_0
  - r-htmlwidgets=1.0=r3.4.1_0
  - r-httpuv=1.3.6.2=r3.4.1_0
  - r-httr=1.3.1=r3.4.1_0
  - r-igraph=1.2.1=r3.4.1_0
  - r-influencer=0.1.0=r3.4.1_0
  - r-irlba=2.3.2=r3.4.1_0
  - r-iterators=1.0.9=r3.4.1_0
  - r-jsonlite=1.5=r3.4.1_0
  - r-knitr=1.20=r3.4.1_0
  - r-labeling=0.3=r3.4.1_0
  - r-lambda.r=1.2=r3.4.1_0
  - r-lattice=0.20_34=r3.4.1_0
  - r-lazyeval=0.2.1=r3.4.1_0
  - r-lubridate=1.7.4=r3.4.1_0
  - r-magrittr=1.5=r3.4.1_0
  - r-markdown=0.8=r3.4.1_1
  - r-mass=7.3_48=r3.4.1_0
  - r-matrix=1.2_14=r3.4.1_0
  - r-matrixstats=0.53.1=r341_0
  - r-memoise=1.1.0=r3.4.1_0
  - r-mgcv=1.8_24=r341_0
  - r-mime=0.5=r3.4.1_0
  - r-mnormt=1.5_5=r3.4.1_0
  - r-modelr=0.1.2=r341_0
  - r-munsell=0.5.0=r341_0
  - r-nlme=3.1_131=r3.4.1_0
  - r-nmf=0.21.0=r3.4.1_0
  - r-openssl=1.0.1=r3.4.1_0
  - r-pheatmap=1.0.10=r341_0
  - r-pillar=1.2.2=r341_0
  - r-pkgconfig=2.0.1=r3.4.1_0
  - r-pkgmaker=0.22=r3.4.1_0
  - r-plogr=0.1_1=r3.4.1_0
  - r-plyr=1.8.4=r3.4.1_0
  - r-praise=1.0.0=r3.4.1_0
  - r-prettyunits=1.0.2=r3.4.1_0
  - r-psych=1.8.4=r341_0
  - r-purrr=0.2.4=r3.4.1_0
  - r-r6=2.2.2=r3.4.1_0
  - r-rcolorbrewer=1.1_2=r3.4.1_0
  - r-rcpp=0.12.15=r3.4.1_0
  - r-rcurl=1.95_4.8=r3.4.1_0
  - r-readr=1.1.1=r3.4.1_0
  - r-readxl=1.1.0=r341_0
  - r-registry=0.5=r3.4.1_0
  - r-rematch=1.0.1=r3.4.1_0
  - r-reshape2=1.4.3=r3.4.1_0
  - r-rgexf=0.15.3=r3.4.1_0
  - r-rlang=0.2.1=r341_0
  - r-rmarkdown=1.9=r341_0
  - r-rngtools=1.2.4=r3.4.1_0
  - r-rook=1.1_1=r3.4.1_0
  - r-roxygen2=6.0.1=r3.4.1_0
  - r-rprojroot=1.3_2=r3.4.1_0
  - r-rsqlite=2.0=r3.4.1_0
  - r-rstudioapi=0.7=r3.4.1_0
  - r-rvest=0.3.2=r3.4.1_0
  - r-scales=0.5.0=r3.4.1_0
  - r-selectr=0.3_1=r3.4.1_0
  - r-shiny=1.0.5=r3.4.1_0
  - r-shinythemes=1.1.1=r3.4.1_0
  - r-snow=0.4_2=r3.4.1_0
  - r-sourcetools=0.1.6=r3.4.1_0
  - r-stringi=1.1.7=r3.4.1_1
  - r-stringr=1.3.0=r3.4.1_0
  - r-survival=2.40_1=r3.4.1_0
  - r-testit=0.6=r3.4.1_0
  - r-testthat=2.0.0=r3.4.1_1
  - r-tibble=1.4.2=r3.4.1_0
  - r-tidyr=0.8.1=r341_0
  - r-tidyselect=0.2.4=r3.4.1_0
  - r-tidyverse=1.1.1=r3.4.1_0
  - r-utf8=1.1.3=r3.4.1_0
  - r-viridis=0.5.1=r3.4.1_0
  - r-viridislite=0.3.0=r3.4.1_0
  - r-visnetwork=2.0.4=r341_0
  - r-whisker=0.3_2=r3.4.1_0
  - r-withr=2.1.1=r3.4.1_0
  - r-xfun=0.2=r341_0
  - r-xml=3.98_1.6=r3.4.1_0
  - r-xml2=1.1.1=r3.4.1_0
  - r-xtable=1.8_2=r3.4.1_0
  - r-yaml=2.1.18=r3.4.1_0
  - readline=7.0=0
  - tk=8.6.7=0
  - xorg-kbproto=1.0.7=1
  - xorg-libice=1.0.9=2
  - xorg-libsm=1.2.2=2
  - xorg-libx11=1.6.5=0
  - xorg-libxau=1.0.8=3
  - xorg-libxdmcp=1.1.2=3
  - xorg-libxext=1.3.3=2
  - xorg-libxrender=0.9.10=0
  - xorg-renderproto=0.11.1=1
  - xorg-xextproto=7.3.0=1
  - xorg-xproto=7.0.31=6
  - xz=5.2.3=0
  - zlib=1.2.11=h470a237_3
  - _r-mutex=1.0.0=mro_2
  - blas=1.0=mkl
  - libgcc=7.2.0=h69d50b8_2
  - libgcc-ng=7.2.0=hdf63c60_3
  - libgfortran=3.0.0=1
  - libstdcxx-ng=7.2.0=hdf63c60_3
prefix: /storage/apps/easybuild/software/Anaconda3/5.0.1/envs/r

